#IMPORTANDO BIBLIOTECAS EXTERNAS (IMPORT)
import math as m #AS M --- ESTOU DANDO UM NOME À ESTA BIBLIOTECA

print(m.sqrt(9))


#OUTRA MANEIRA

from math import sqrt #IMPORTA SOMENTE A FUNÇÃO QUE VOCÊ QUER, DEIXANDO DE FORA TODAS AS OUTRAS

#OUTRA MANEIRA 2